### ISSUE TITLE
MySQL failover?

### ISSUE THREAD

**Issue by telefax** [tagomoris/fluent-plugin-mysql#30]
Can I have multiple mysql servers specified somehow for redundancy?

I have master-master MySQL instances, in case of one of them goes down I'd like my data to be sent to the other server.

Normally I would use floating IP (using something like keepalived) but in this case, the mysql instances are on different OS and architecture which does not have keepalived ported.

Would it be possible to have it retry with another MySQL server if the first isn't alive?
I guess there could be a slight performance penalty for this.

**Comment by tagomoris** [comment]
Use `<secondary>` output.
http://docs.fluentd.org/articles/output-plugin-overview#secondary-output

**Comment by telefax** [comment]
Ah, excellent!
Thanks for pointing it out in the fluentd manual :+1:
