### ISSUE TITLE
Encoding::UndefinedConversionError: "\xE3" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by t-cyrill** [tagomoris/fluent-plugin-mysql#46]
Hi, I'm using fluent-plugin-mysql's `mysql_bulk` to write to mysql 5.7 database.

When in_tail plugin read a line contains multibyte string (i.e Japanese "ほげ"), it cannot encode json_column.

It seems to `String.to_json` from `yajl` problem.

I tried to use `oj` to avoid a problem. But it's workaround right?
Please tell me better way.

Thank you for reading.

**Comment by catatsuy** [comment]
This issue has been resolved. Please close.

**Comment by toyama0919** [comment]
released, thanks 👍 

[fluent\-plugin\-mysql \| RubyGems\.org \| your community gem host](https://rubygems.org/gems/fluent-plugin-mysql/versions/0.3.1)

**Comment by t-cyrill** [comment]
Thanks👍
